services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Porthd\Timer\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Porthd\Timer\Command\UpdateTimerCommand:
        tags:
            -   name: 'console.command'
                command: 'timer:updateTimerCommand'
                description: 'Update starttime and endtime in various tables, where a timer is defined.'

    Porthd\Timer\Services\HolidaycalendarService:
        public: true

    cache.timer_dataprocessor:
        class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
        factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
        arguments: [ 'timer_dataprocessor' ]

    cache.timer_manager:
        class: \TYPO3\CMS\Extbase\Service\CacheService

    cache.timer_contentdataprocessor:
        class: TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor

    cache.timer_periodlisttimer:
        class: Porthd\Timer\CustomTimer\PeriodListTimer

    cache.timer_yamlfileloader:
        class: TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader

    Porthd\Timer\DataProcessing\HolidaycalendarProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\PeriodlistProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $periodListTimer: '@cache.timer_periodlisttimer'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\RangeListQueryProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\FlexToArrayProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\BetterMappingProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\PhpMappingProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\SortListQueryProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'
