services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Porthd\Timer\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Porthd\Timer\Command\UpdateTimerCommand:
        tags:
            -   name: 'console.command'
                command: 'timer:updateTimerCommand'
                description: 'Update starttime and endtime in various tables, where a timer is defined.'

    Porthd\Timer\Services\HolidaycalendarService:
        public: true
