services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Porthd\Timer\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Porthd\Timer\Backend\FlexFormParsingModifyEventListener:
        tags:
            -   name: event.listener
                identifier: 'form-framework/modify-data-structure'
                method: 'modifyDataStructure'

    Porthd\Timer\Command\UpdateTimerCommand:
        tags:
            -   name: 'console.command'
                command: 'timer:updateTimerCommand'
                description: 'Update starttime and endtime in various tables, where a timer is defined.'
        arguments:
            $listOfTimerService: '@cache.timer_listOfTimerService'
            $dataHandler: '@cache.timer_datahandler'
            $yamlLoader: '@cache.timer_yamlfileloader'
            $pageTreeRepository: '@core.pagetree'

    Porthd\Timer\Services\HolidaycalendarService:
        public: true

    core.pagetree:
        class: TYPO3\CMS\Backend\Tree\Repository\PageTreeRepository

    cache.timer_dataprocessor:
        class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
        factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
        arguments: [ 'timer_dataprocessor' ]

    cache.timer_manager:
        class: TYPO3\CMS\Extbase\Service\CacheService

    cache.timer_listOfTimerService:
        class: Porthd\Timer\Services\ListOfTimerService

    cache.timer_pageTreeRepository:
        class: TYPO3\CMS\Backend\Tree\Repository\PageTreeRepository

    cache.timer_datahandler:
        class: TYPO3\CMS\Core\DataHandling\DataHandler

    cache.timer_contentdataprocessor:
        class: TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor

    cache.timer_periodlisttimer:
        class: Porthd\Timer\CustomTimer\PeriodListTimer

    cache.timer_yamlfileloader:
        class: TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader

    Porthd\Timer\DataProcessing\HolidaycalendarProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\PeriodlistProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $periodListTimer: '@cache.timer_periodlisttimer'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\RangeListQueryProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\FlexToArrayProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\BetterMappingProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'

    Porthd\Timer\DataProcessing\PhpMappingProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $yamlFileLoader: '@cache.timer_yamlfileloader'

    Porthd\Timer\DataProcessing\SortListQueryProcessor:
        arguments:
            $cache: '@cache.timer_dataprocessor'
            $cacheManager: '@cache.timer_manager'
            $contentDataProcessor: '@cache.timer_contentdataprocessor'
